from pathlib import Path
import os
from single_source import get_version
import base64

_ver_path = Path(__file__).parent.parent
__version__ = get_version(__name__, _ver_path)

if os.environ.get("DEBUG") == "1":
    print('ver:', __version__, '_ver_path:', _ver_path)

ICON_ART = base64.b64decode(
    """ICAgICAgLiwsLCwsLCwsLCwsLCwsICAgLOKVn+KWhCzilpMsIC4sLCwsLCwsLCwKICAgICAg4paQ4paI4paT4paT4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paMICDilojilojilozilZnilogiIOKWkOKWiOKWiOKWiOKWiOKWiOKWiOKWk+KWk+KWiOKWjAogICAgICDilpDilojilpPilpPilojilojilojilojilojilojilojilojilojilojilojilowgIOKWiOKWiOKWiOKWhOKWiOKVmSDilpDilojilojilojilojilojilojilpPilpPilojilowKICAgICAg4paQ4paI4paI4paA4paA4paAICAgICAgICAgICAgICAgICAgICAgICAg4paQ4paI4paI4paI4paI4paMCiAgICAgIOKWkOKWiOKWiCDilZ/ilazilazilazilazilazilazilazilazilaxNasORw5EgICAgICDCquKVqVIgICDilpDilojilojilojilojilowKICAgICAg4paQ4paI4paIIOKVn+KWk+KWk+KWk+KWk+KWk+KWk+KWk+KWk+KWk01q4pWr4pWrICAgICBgYGBgYCAg4paQ4paI4paI4paI4paI4paMCiAgICAgIOKWkOKWiOKWiCDilZ/ilpPilpPilpPilpPilpPilpPilpPilpPilpNNauKVq+KVqyAgICAgICAgICAgIOKWkOKWiOKWiOKWiOKWiOKWjAogICAgICAs4paE4paEIOKVn+KWk+KWk+KWkyAgICDilpPilpNNauKVq+KVqyAgICAgIOKVk+KVpeKJpCAgICziloTiloTiloTiloTilZUKICAgICAg4paQ4paI4paIIOKVn+KWk+KWk+KWkyAgICDilpPilpNNauKVq+KVqyAgICAgIOKVq+KVq8ORICAg4paQ4paI4paI4paI4paI4paMCiAgICAgIOKWkOKWiOKWiCDilZ/ilpPilpPilpPOps6mzqbOpuKWk+KWk01q4pWr4pWrICAgICAg4pWr4pWrw5EgICDilpDilojilojilojilojilowKICAgICAg4paQ4paI4paIIOKVn+KWk+KWk+KWk+KWk+KWk+KWk+KWk+KWk+KWk01q4pWr4pWrICAgICAgIiIiICAg4paQ4paI4paI4paI4paI4paMCiAgICAgIOKWkOKWiOKWiCDilZnilZzilZzilZzilZzilZzilZzilZzilZzilZxgIuKVqOKVqCAgICAgIOKVn+KWk+KWjCAgIOKWkOKWiOKWiOKWiOKWiOKWjAogICAgICDilpDilojilojilojilojilozilZPilZPilZPilZPilZPilZPilZPilZMn4pWa4pWd4pWdICzilZPilZPilZMg4pWa4paA4paAIOKVk+KVk+KWhOKWiOKWiOKWiOKWiOKWjAogICAgICDilpDilojilavilavilojilojilojilojilojilojilojilojilojilojilojilowgIOKWk+KWiOKWjOKWkOKWiM6m4oyQ4paQ4paT4paT4paI4paI4paI4paI4pWr4pWr4paI4paMCiAgICAgIOKWkOKWiOKWk+KWk+KWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWjCAg4paI4paI4paI4paE4paI4pWXIOKWkOKWiOKWiOKWiOKWiOKWiOKWiOKWk+KWkwo=""") \
        .decode()